---
development:
  cloud_name: chayner
  api_key: '815882169577879'
  api_secret: CgHgSrBKQ6NzCBXESVTUki9fTRg
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: chayner
  api_key: '815882169577879'
  api_secret: CgHgSrBKQ6NzCBXESVTUki9fTRg
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: chayner
  api_key: '815882169577879'
  api_secret: CgHgSrBKQ6NzCBXESVTUki9fTRg
  enhance_image_tag: true
  static_image_support: false
